apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-task1
  namespace: my-ns
  labels:
    app: cycle
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cycle
  template:
    metadata: 
      labels:
        app: cycle
    spec:
      containers:
        - name: nginx
          image: shammu101/cycle
          ports:
            - containerPort: 80
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: config1
                  key: URL
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  name: config1
                  key: NAME
            - name: PLACE
              valueFrom:
                configMapKeyRef:
                  name: config1
                  key: PLACE
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: config1
                  key: PORT

---
apiVersion: v1
kind: Service
metadata:
  name: svc-task1
  namespace: my-ns
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: cycle
