apiVersion: v1
kind: Pod
metadata:
  name: dep1
  namespace: my-ns
  labels:
    app: dm
spec:
  containers:
    - name: cont1
      image: shammu101/dm
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  namespace: my-ns
spec:
  type: NodePort
  selector:
    app: dm
  ports: 
    - port: 80
      targetPort: 80
